pm_site/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from project.views import LoginView

admin.autodiscover()

urlpatterns = patterns('',
    url(
        regex = '^accounts/login/$', 
        view = LoginView.as_view(),
        name = 'login'
    ),
    url(
        regex = '^accounts/logout/$', 
        view = 'django.contrib.auth.views.logout', 
        kwargs = {'next_page': '/accounts/login/'},
        name = 'logout'
    ),
    url(
        regex = '^todo/',
        view = include('project.urls', namespace='project', app_name='project')
    ),
    url(
        regex = '^admin/', 
        view = include(admin.site.urls)
    ),
)

project/urls.py
from django.conf.urls import patterns, url
from project.views import ToDoListView, ToDoCreateView, ToDoDeleteView, ToDoUpdateView, TaskCreateView, TaskDeleteView


urlpatterns = patterns('',
    url (
           regex = '^$',
           view =  ToDoListView.as_view(),
           name = 'todo_list'
       ),
    url (
           regex = '^create/$',
           view =  ToDoCreateView.as_view(),
           name = 'todo_create'
       ),
    url (
           regex = '^delete/(?P<pk>\d+)/$',
           view =  ToDoDeleteView.as_view(),
           name = 'todo_delete'
       ),
    url (
           regex = '^update/(?P<pk>\d+)/$',
           view =  ToDoUpdateView.as_view(),
           name = 'todo_update'
       ),
    url (
           regex = '^(?P<todo>\d+)/task/create/$',
           view =  TaskCreateView.as_view(),
           name = 'task_create'
       ),
    url (
           regex = '^(?P<todo>\d+)/task/delete/(?P<pk>\d+)/$',
           view =  TaskDeleteView.as_view(),
           name = 'task_delete'
       ),
)

project/models.py
from django.contrib.auth.models import User
from django.db import models


class ToDo(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    created_by = models.ForeignKey(User)
    name = models.CharField(max_length=255)
    
    def __unicode__(self):
        return self.name
    
    
class Task(models.Model):
    STATUS_CHOICES = (
        ('R', 'RESOLVED'),
        ('O', 'OPEN'),
    )
    
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    todo = models.ForeignKey(ToDo)
    name = models.CharField(max_length=255)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    
    def __unicode__(self):
        return self.name

project/forms.py
from django.forms import ModelForm

from .models import ToDo, Task
        

class ToDoForm(ModelForm):
    class Meta:
        model = ToDo
        exclude = ('created_by',)
        
    
class TaskForm(ModelForm):
    class Meta:
        model = Task
        exclude = ('todo', 'created_by', 'status')

project/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, FormView

from .forms import ToDoForm, TaskForm
from .models import ToDo, Task


class LoginView(FormView):
    form_class = AuthenticationForm
    template_name = 'project/login.html'
    
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        return super(LoginView, self).dispatch(*args, **kwargs)
    
    def get_success_url(self):
        return reverse('project:todo_list')
    
    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(LoginView, self).form_valid(form)
    

class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)


class ToDoMixin(LoginRequiredMixin):
    model = ToDo
    form_class = ToDoForm
    
    def get_success_url(self):
        return reverse('project:todo_list')
    
    def get_queryset(self):
        #return Task.objects.filter(todo__project=self.kwargs['project']).select_related('todo')
        return ToDo.objects.filter(created_by=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(ToDoMixin, self).get_context_data(**kwargs)
        return context
    
    def form_valid(self, form):
        self.todo_list = form.save(commit=False)
        self.todo_list.created_by = self.request.user
        self.todo_list.save()
        return super(ToDoMixin, self).form_valid(form)


class ToDoListView(ToDoMixin, ListView):
    pass


class ToDoDetailView(ToDoMixin, DetailView):
    pass


class ToDoCreateView(ToDoMixin, CreateView):
    pass


class ToDoDeleteView(ToDoMixin, DeleteView):
    pass


class ToDoUpdateView(ToDoMixin, UpdateView):
    pass


class TaskMixin(LoginRequiredMixin):
    model = Task
    form_class = TaskForm
    
    def get_success_url(self):
        return reverse('project:todo_list')
    
    def get_queryset(self):
        return Task.objects.filter(todo=self.kwargs['todo'], todo__created_by=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(TaskMixin, self).get_context_data(**kwargs)
        return context
    
    def form_valid(self, form):
        self.task = form.save(commit=False)
        self.task.created_by = self.request.user
        self.task.todo = get_object_or_404(ToDo, pk=self.kwargs['todo'])
        self.task.save()
        return super(TaskMixin, self).form_valid(form)


class TaskCreateView(TaskMixin, CreateView):
    pass


class TaskDeleteView(TaskMixin, DeleteView):
    pass

pm_site/templates/_layouts/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>{% block page_title %}{% endblock %}</title>
	</head>
	<body>
		<header>
			<nav>
			{% if user.is_authenticated %}
			    <a href="{% url project:todo_list %}">To do list</a>
			    <a href="{% url logout %}">logout</a>
			{% endif %}
			</nav>
		</header>
		{% block page_content %}{% endblock %}
	</body>
</html>

project/templates/project/login.html
{% extends "_layouts/base.html" %}

{% block page_title %}Projects{% endblock %}

{% block page_content %}
<form action="." method="POST">{{ form }}{% csrf_token %}
    <input type="submit" value="Go" />
</form>
{% endblock %}

project/templates/project/task_confirm_delete.html
<h1>Resolve This?</h1>
{{ object }}
<form action="." method="post">{% csrf_token %}
    <input type="submit" value="Resolve" />
</form>

project/templates/project/task_form.html
<form action="." method="POST">{{ form }}{% csrf_token %}
    <input type="submit" value="Go" />
</form>

project/templates/project/todo_confirm_delete.html
<h1>Delete This?</h1>
{{ object }}
<form action="." method="post">{% csrf_token %}
    <input type="submit" value="Delete" />
</form>

project/templates/project/todo_form.html
<form action="." method="POST">{{ form }}{% csrf_token %}
    <input type="submit" value="Go" />
</form>

project/templates/project/todo_list.html
{% extends "_layouts/base.html" %}

{% block page_title %}{{ todo.name }}{% endblock %}

{% block page_content %}
<div>
<h2>To-Do list</h2>
<a href="{% url project:todo_create %}">Create new To-Do</a>
{% for todo in todo_list %}
    <h3>{{ todo.name }} <a href="{% url project:todo_update todo.id %}">edit</a> <a href="{% url project:todo_delete todo.id %}">delete</a></div></h3>
    {% for task in todo.task_set.all %}
        <p>{{ task.name }} <a href="{% url project:task_delete todo.id task.id %}">resolve</a></p>
    {% empty %}
    {% endfor %}
    <a href="{% url project:task_create todo.id %}">Create new Task</a>
{% empty %}
    No To-Dos.
{% endfor %}
</div>
{% endblock %}